on: ["push", "pull_request"]

name: main workflow

env:
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Compiler Installations
      uses: actions/cache@v3
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
        cache: "pip"

    - name: Install Requirements
      run: pip install -r requirements_complete.txt

    - name: Format Python
      run: |
        black --version
        black . --check

    - name: Format Vyper
      run: |
        python3 -c "import mamushi; print(mamushi.__version__)"
        mamushi . --check

    - name: Lint Python
      run: |
        flake8 .

    - name: Run Tests
      run: |
        touch .env
        echo "WEB3_INFURA_PROJECT_ID=${{ env.WEB3_INFURA_PROJECT_ID }}" >> .env
        echo "ETHERSCAN_TOKEN=${{ env.ETHERSCAN_TOKEN }}" >> .env
        pytest
